src/main/java/mods/eln/i18n/LanguageFileUpdater.java
src/main/java/mods/eln/mechanical/Generator.kt
src/main/java/mods/eln/sixnode/Scanner.kt
src/main/java/mods/eln/sixnode/electricalbreaker/ElectricalBreakerDescriptor.java
src/main/java/mods/eln/sixnode/electricalcable/ElectricalCableDescriptor.java
src/main/java/mods/eln/sixnode/electricalgatesource/ElectricalGateSourceDescriptor.java
src/main/java/mods/eln/sixnode/electricalgatesource/ElectricalGateSourceElement.java
src/main/java/mods/eln/sixnode/electricalrelay/ElectricalRelayDescriptor.java
src/main/java/mods/eln/sixnode/electricalwatch/ElectricalWatchDescriptor.java
src/main/java/mods/eln/sixnode/lampsupply/LampSupplyDescriptor.java
src/main/java/mods/eln/sixnode/wirelesssignal/source/WirelessSignalSourceDescriptor.java
src/main/java/mods/eln/sixnode/wirelesssignal/source/WirelessSignalSourceElement.java
src/main/java/mods/eln/transparentnode/LargeRheostat.kt
src/main/java/mods/eln/transparentnode/battery/BatteryElement.java
src/main/java/mods/eln/transparentnode/teleporter/TeleporterDescriptor.java
src/main/java/mods/eln/transparentnode/thermaldissipatorpassive/ThermalDissipatorPassiveDescriptor.java
src/main/resources/assets/eln/lang/en_US.lang

Not ready for merge yet. Just a progress holder.
See #12 for more details on what started all of this.

lots of progress on the lang project

---

src/main/java/mods/eln/Eln.java
src/main/resources/assets/eln/lang/en_US.lang

Fixes #5 
Might want to merge in the changes from upstream's lang file.

Fixed using sigbus renderer on various signal things

---

src/main/java/mods/eln/misc/Utils.java

Added microfarad support, fixed in upstream as well.

added microfarad support

---

src/main/java/mods/eln/node/six/SixNodeBlock.java
src/main/java/mods/eln/node/six/SixNodeCacheStd.java

Fixed Quartz/Log/Grass/Leaves on SixNode

---

src/main/java/mods/eln/Eln.java

changed to 8 lead around a machine part

---

src/main/java/mods/eln/packets/TransparentNodeResponsePacket.kt
src/main/java/mods/eln/sixnode/electricalcable/ElectricalSignalBusCableElement.java

Working on Issue #5 
The colors are somewhat there. I'm having a difficult problem with getting them in order. I suspect either Waila is strange and does things out of order, or my math skills are poor (but it could be both!)
Waila doesn't work with newlines, you need to have next line's items in the list (which needs a non duplicated key name for a map?). Thus, I split the cable into 4 "channels".

some progress

---

src/main/java/mods/eln/mechanical/Motor.kt

- Clamped volume (fixes #30)
- Made them very, very poor generators
- Fixed a floating voltage bug (upstream from devel-shaft-objects)
- Adjusted their coloration/volume scale to be more sensible

Fixed motors in various ways:

---

src/main/resources/assets/eln/lang/pt.lang
src/main/resources/assets/eln/lang/pt_BR.lang

Fixes #36 and #49
It gets further at least. May still have some work to do with the new additions

adding pt and pt_BR language files

---

src/main/java/mods/eln/mechanical/Motor.kt

(This hopefully rebalances after the last nerfing to fix an infinite
energy bug.)

Triple motor current draw

---

src/main/java/mods/eln/sim/process/destruct/VoltageStateWatchDog.java

cherry-picked for jrddunbr's fork

Attempt supporting negative voltage

---

src/main/java/mods/eln/server/ConsoleListener.java
src/main/java/mods/eln/sim/mna/RootSystem.java
src/main/java/mods/eln/sim/mna/SubSystem.java
src/main/java/mods/eln/sim/mna/component/Bipole.java
src/main/java/mods/eln/sim/mna/component/Component.java
src/main/java/mods/eln/sim/mna/state/State.java

This allows one to see how many matrices there are, and to export the file of current matrices.
There are a few considerations I need to do:
* Only allow operators to run the program. This also prevents TPS problems by restricting users.
I have already considered the following:
* cannot fill the disk because it overwrites the old version.

added export stuff

---

src/main/java/mods/eln/Eln.java

added crafting for nixies and digital displays

---

src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerDescriptor.java
src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerElement.java
src/main/java/mods/eln/sixnode/electricaldatalogger/ElectricalDataLoggerRender.java

Data loggers are now colorable

---

src/main/java/mods/eln/sim/BatteryProcess.java
src/main/java/mods/eln/sim/nbt/NbtBatteryProcess.java
src/main/java/mods/eln/transparentnode/battery/BatteryElement.java

batteries no longer recharge if they can't do that

---

src/main/java/mods/eln/Eln.java
src/main/java/mods/eln/client/VersionCheckerHandler.java

* reduce excessive naming stuff

That's less horrible. That was exessive

---

src/main/java/mods/eln/Eln.java
src/main/java/mods/eln/mechanical/ShaftNetwork.kt

This is a requested change to the shaft energy storage, and fixes a bug where split networks would have no speed.

Add shaft energy factor, fix a network splitting bug

---

src/main/java/mods/eln/Eln.java
src/main/java/mods/eln/sixnode/lampsocket/LampSocketDescriptor.java

Fixed street lamp rendering in hand

---

src/main/java/mods/eln/sixnode/electricalsensor/ElectricalSensorElement.java
src/main/java/mods/eln/sixnode/powercapacitorsix/PowerCapacitorSixElement.java
src/main/java/mods/eln/sixnode/powerinductorsix/PowerInductorSixElement.java
src/main/java/mods/eln/sixnode/thermalsensor/ThermalSensorElement.java

Specifically affecting:
- Inductors
- Capacitors
- Sensors of all kinds
Fixes #115.

Fixed some sync issues with the CCT

---

src/main/java/mods/eln/mechanical/ShaftNetwork.kt

This should hopefully help people who are wont to make large shaft
networks, since the old calculations for mass would cause performance to
degrade quadratically.
Preliminary testing seems to show that performance improvements are in
the realm of ~15%, at most 25%, and certainly not worse than it was
before.
@jrddunbr if you have a profiling world, this would be a good one to test on.
Fixes #124.

Cached important shaft variables

---

src/main/java/mods/eln/sixnode/electricalcable/ElectricalCableDescriptor.java

Fix problems with variable overlap

fixed variable overlap

---

src/main/java/mods/eln/transparentnode/autominer/AutoMinerSlowProcess.java

Fix for Issue #141 - Autominer using full chest

---

src/main/java/mods/eln/Eln.java

Battery and 200V machine draw upgrades, nothing more.

Haxorian Balance Changes, updated to 1.15.x-stable

---

src/main/java/mods/eln/sim/mna/RootSystem.java
src/main/java/mods/eln/sixnode/electricalcable/ElectricalCableElement.java
src/main/java/mods/eln/transparentnode/variabledcdc/VariableDcDc.kt

Hotfix vdcdc

---

src/main/java/mods/eln/node/six/SixNodeEntity.java

Be more vigilant in testing for nulls from deserialized network IDs.
This code builds, but is untested.
Tracking labels: this PR
* resolves #206

hotfix-net: Proposed fix for #206

---

src/main/java/mods/eln/node/six/SixNodeEntity.java
src/main/java/mods/eln/sixnode/energymeter/EnergyMeterRender.java

Fixes #206. See commit messages for details.

hotfix-net: Fixes #206 once and for all

---

src/main/java/mods/eln/transparentnode/variabledcdc/VariableDcDc.kt

Added word "Copper" to VDC's GUI

---

src/main/java/mods/eln/sixnode/lampsocket/LampSocketProcess.kt

- Fixed a problem so that the in game message "conntected to" now works correctly.
- Fixed a bug that prevent sometimes the correct update of the light.
- Fixed "java.util.NoSuchElementException: List is empty" exception in lamp socket.

Fixed bugs in LampSocketProcess

---

src/main/java/mods/eln/transparentnode/dcdc/DcDc.kt
src/main/java/mods/eln/transparentnode/dcdc/LegacyDcDc.kt

- Fixed a bug that destroys all transformers on the map (happend to me on my server  :( ), because the ratio was inverted.

Fixed a bug in the calculation of the transformer ratio 

---

src/main/java/mods/eln/transparentnode/turbine/TurbineThermalProcess.java

Potentially fixes an (unattested here) issue by @OmegaHaxors wherein (heat) turbines can be exploited due to their lack of thermal energy conservation.

Conserve energy

---

src/main/java/mods/eln/sixnode/electricalsensor/ElectricalSensorContainer.java
src/main/java/mods/eln/sixnode/electricalsensor/ElectricalSensorElement.java
src/main/java/mods/eln/sixnode/thermalsensor/ThermalSensorContainer.java
src/main/java/mods/eln/sixnode/thermalsensor/ThermalSensorElement.java
src/main/java/mods/eln/sixnode/thermalsensor/ThermalSensorRender.java

Added current cable support to electrical probe, voltage probe and temperature probe.
I tested it and it should be working fine.

Added current cable support to probes

---

src/main/java/mods/eln/transparentnode/FuelHeatFurnace.kt

Fix Fuel Heat Furnace (#272)

---

src/main/java/mods/eln/fluid/ElementSidedFluidHandler.kt
src/main/java/mods/eln/fluid/PreciseElementSidedFluidHandler.kt
src/main/java/mods/eln/fluid/TankData.kt

Allows for precise emptying of fluids with the use of a fixup value.
This should allow for usage with the steam turbine in the future...

Adds new PreciseElementSidedFluidHandler 

---

build.gradle
gradle.properties
src/main/java/mods/eln/Eln.java
src/main/java/mods/eln/integration/minetweaker/Machines.kt
src/main/java/mods/eln/integration/minetweaker/MinetweakerIntegration.kt
src/main/java/mods/eln/integration/minetweaker/Utils.kt

Title.
Copies from https://github.com/Electrical-Age/ElectricalAge/pull/478/files

Adds basic MineTweaker3 Support

---

src/main/kotlin/mods/eln/sixnode/lampsocket/LampSocketProcess.kt

Fix NPE in lamp supply
